---
driver:
  name: vagrant
  vm_hostname: probe
  customize:
    memory: 4096
    cpus: 1
    name: probe
  network:
   - ['private_network', ip: <%= ENV['PSP'] %>]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  # always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: mycsc-7.4

suites:
  - name: objsrv
    run_list:
#      - recipe[objsrv::do_prs]
      - recipe[objsrv::make_ncp81]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
