---
driver:
  name: vagrant
  vm_hostname: <%= ENV['PS'] %>
  customize:
    memory: <%= ENV['PSR'] %>
    cpus: <%= ENV['PSC'] %>
    name: <%= ENV['PS'] %>
  network:
   - ['private_network', ip: <%= ENV['PSP'] %>]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  # always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: mycsc-7.6

suites:
  - name: prbsrv
    run_list:
#      - recipe[objsrv::do_prs]
      - recipe[prbsrv::make_nc_ps]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
