name 'prbsrv'
maintainer 'Ed Overton'
maintainer_email 'bogus@gmail.com'
chef_version '>= 13.0'
license 'Apache-2.0'
description 'Installs/Configures prbsrv'
version '0.4.4'
supports 'redhat'
supports 'centos'

issues_url 'https://github.com/emo3/prbsrv/issues'
source_url 'https://github.com/emo3/prbsrv'

depends 'nc_base'
depends 'nc_tools'
depends 'server_utils'
