default['objsrv']['base_ver']    = '8.1.0'
default['objsrv']['point_ver']   = "#{node['objsrv']['base_ver']}.1"
default['objsrv']['fp_ver']      = '15'
default['objsrv']['fp_pkg']      = "#{node['objsrv']['base_ver']}-TIV-NCOMNIbus-Linux-FP00#{node['objsrv']['fp_ver']}.zip"
default['objsrv']['fp_rel']      = '5.50.73.20171113_0327'
default['objsrv']['package']     = "OMNIbus-v#{node['objsrv']['point_ver']}-Core.linux64.zip"
default['objsrv']['im_ver']      = '1.8.8000.20171130_1105'
default['objsrv']['im_pkg']      = "agent.installer.linux.gtk.x86_64_#{node['objsrv']['im_ver']}.zip"
default['objsrv']['prs']         = '1.2.0.18-Tivoli-PRS-Unix-fp0001.tar'
default['objsrv']['cots_dir']    = '/sfcots'
default['objsrv']['app_dir']     = "#{node['objsrv']['cots_dir']}/apps"
default['objsrv']['nc_dir']      = "#{node['objsrv']['app_dir']}/netcool"
default['objsrv']['media_dir']   = "#{node['objsrv']['app_dir']}/media"
default['objsrv']['install_dir'] = "#{node['objsrv']['media_dir']}/nco81"
default['objsrv']['fp_dir']      = "#{node['objsrv']['media_dir']}/nco81fp"
default['objsrv']['gate_dir']    = "#{node['objsrv']['media_dir']}/gateways"
default['objsrv']['nckl_dir']    = "#{node['objsrv']['media_dir']}/nckl"
default['objsrv']['temp_dir']    = '/tmp'
default['objsrv']['im_dir']      = '/tmp/im'
default['objsrv']['media_url']   = 'http://10.1.1.30/media'
# default['objsrv']['rhel']        = %w(bc ntp firefox libXtst compat-libstdc++-33.i686)
default['objsrv']['rhel']        = %w(bc ntp firefox compat-libstdc++-33.i686 libXtst.i686 compat-libstdc++-33 compat-db libXp libXmu libXtst pam libXft gtk2 xauth)
default['objsrv']['nc_act']      = 'netcool'
default['objsrv']['nc_grp']      = 'ncoadmin'
default['objsrv']['nc_pwd']      = '$1$xyz$KYGw.YHIMKWpbx6InG1H9/'
