default['prbsrv'].tap do |prb|
  prb['app_dir']     = "/apps"
  prb['nc_dir']      = "#{node['prbsrv']['app_dir']}/netcool"
  prb['ob_dir']      = "#{node['prbsrv']['nc_dir']}/omnibus"
  prb['prb_dir']     = "#{node['prbsrv']['ob_dir']}/probes"
  prb['media_dir']   = "#{node['prbsrv']['app_dir']}/media"
  prb['install_dir'] = "#{node['prbsrv']['media_dir']}/ncp81"
  prb['temp_dir']    = '/tmp'
  prb['media_url']   = 'http://10.1.1.30/media'
  prb['lv_name']     = 'lvnc'
  prb['lv_size']     = '40G'
  prb['nc_act']      = 'netcool'
  prb['nc_grp']      = 'ncoadmin'
  prb['ncoms']       = 'NCO'
  prb['arch']        = 'linux2x86'
  prb['OS']          = 'eao'
  prb['OSP']         = '10.1.1.40'
  prb['PS']          = 'eap'
  prb['PSP']         = '10.1.1.41'
end
